apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  name: gobg-internal
  namespace: default
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gobg
  name: gobg
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: gobg
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gobg
  name: gobg
spec:
  replicas: 20
  selector:
    matchLabels:
      app: gobg
  strategy: {}
  template:
    metadata:
      labels:
        app: gobg
    spec:
      containers:
      - image: christianh814/gobg:latest
        name: gobg
        resources:
          limits:
            memory: 512MiB
          requests:
            cpu: 200m
            memory: 512MiB
