apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: prometheus-pushgateway
    app.kubernetes.io/version: v1.7.0
    helm.sh/chart: prometheus-pushgateway-2.8.0
  name: prometheus-prometheus-pushgateway
  namespace: prometheus
